services:
  mysql:
    image: mysql:8.0.35
    container_name: cstar_mysql
    volumes:
      - ./db/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DEV_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DEV_MYSQL_DATABASE_NAME}
      MYSQL_USER: ${DEV_MYSQL_USER}
      MYSQL_PASSWORD: ${DEV_MYSQL_PASSWORD}
    networks:
      - cstar
  redis:
    image: redis:7.4.0
    container_name: cstar_redis
    ports:
      - "6379:6379"
    networks:
      - cstar

networks:
  cstar:
