server:
  port: 8080
spring:
  config:
    activate:
      on-profile: local
  application:
    name: cstar
  datasource:
    url: jdbc:mysql://localhost:3306/cstar_db
    username: local_user
    password: local_password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      data-locations:
        - classpath:/db/init_schema.sql
        - file:src/main/resources/db/v2_alter_member_table_for_unique.sql
  data:
    redis:
        host: localhost
        port: 6379

jwt:
  secret: eWpoLWNzdGFyLWJhY2tlbmQtand0LXNlY3JldC1rZXkteWpoLWNzdGFyLWJhY2tlbmQtand0LXNlY3JldC1rZXkK
  token-validity-in-seconds: 86400
