name: test

on:
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test:
    name: 테스트
    runs-on: ubuntu-22.04
    steps:
      - name: 레포지토리를 체크아웃
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: JDK 21 설치
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: 빌드 및 테스트
        run: ./gradlew clean build